name = "gbor"
version = "1.0.0"

description = "A Gleam implementation of the CBOR standard"
licences = ["Apache-2.0"]
repository = { type = "github", user = "Beaudidly", repo = "https://github.com/Beaudidly/gbor" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
ieee_float = ">= 1.5.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
